### ISSUE TITLE
携带子路径代理无效

### ISSUE THREAD

**Issue by shengbeiniao** [dora-js/dora-plugin-proxy#108]
例如
规则: '/api/sms/*': 'http://localhost:9000'

发送http://localhost:3000/api/sms/provider

9000端口接收/api/sms/provider全路径，即便改为'http://localhost:9000/也一样

目标：需转发到http://localhost:9000/provider，不能携带子路径

**Comment by sorrycc** [comment]
试试：

```
'/api/sms/(.*)': 'http://localhost:9000'
```

**Comment by shengbeiniao** [comment]
nice!惊呼这响应速度
