### ISSUE TITLE
文档太少了，没搞懂参数怎么传

### ISSUE THREAD

**Issue by yxqme** [dora-js/dora-plugin-proxy#109]
`"dora --plugins \"proxy?watchDirs=/mock/,browser-history,webpack?publicPath=/,webpack-hmr\"",`

watchDirs 如何支持多个文件夹？

**Comment by sorrycc** [comment]
https://github.com/sorrycc/roadhog/issues/22
可以关注 roadhog 的这个 issue，依赖的文件会自动 watch，这周五发布。

**Comment by yxqme** [comment]
好的，谢谢

**Comment by sorrycc** [comment]
roadhog 已支持 mock 。
