### ISSUE TITLE
forward 增强，支持截取部分路径补充到目标服务器

### ISSUE THREAD

**Issue by sorrycc** [dora-js/dora-plugin-proxy#12]
- 如果规则是：`'/a/*': 'http://b.com/b/'` 那么代理 `/a/xxx` 到 `http://b.com/b/a/xxx`
- 如果规则是：`'/a/(.*)': 'http://b.com/b/'` 那么代理 `/a/xxx` 到 `http://b.com/b/xxx`

**Comment by saiyagg** [comment]
什么场景下需要这种规则，如果我就是想把  `/a/xxx` 代理到  `http://b.com/b/`, 那匹配规则该如何写？ @sorrycc

**Comment by sorrycc** [comment]
## 背景

比如 sofa-rest 的开发，需要把 `/api/*` 代理到另一个服务器 `http://localhost:1234/` 下，但是 `http://localhost:1234/` 下又没有 `api` 这个路径。举个这个需求的具体例子：

> 请求 `/api/app/success` 代理到 `http://localhost:1234/app/success`

## 问题

但是现在的配置不能满足需求，比如配置：

```
'/api/*' : 'http://localhost:1234/
```

访问 `/api/app/success` 会被代理到 `http://localhost:1234/api/app/success`。即代理时会附上全路径，缺少路径的截取功能。

## 需求

我之前想的方式是通过 `()` 来表示路径截取，和正则的思路一致，会比较好理解。

配置：

```
'/api/(.*)': 'http://localhost:1234/'
```

请求 `/api/app/success` 会被代理到 `http://localhost:1234/app/success` 。

**Comment by janlay** [comment]
看到有点晚了，感觉 @sorrycc 写的规则并不直观。看上去，要做路径映射的时候:
- 如果希望代理 `/a/xxx` 到 `http://b.com/b/a/xxx`，配置为 `"/a/": "http://b.com/b/a/"`
- 如果希望代理 `/a/xxx` 到 `http://b.com/b/xxx`，配置为 `"/a/": "http://b.com/b/"`

这样，规则就统一为把左边的路径映射（替换）为右边的，更简单易懂。

**Comment by sorrycc** [comment]
规则的左边是一个 url 匹配规则，而不是简单的字符串。如果改成这样，会和其他规则不兼容。

**Comment by janlay** [comment]
统一的匹配规则，建议要么要 plain text, 要么用标准的 regexp (可以学习 nginx rewrite rules), 现在这个 pattern, 说实话有点不上不下。

**Comment by sorrycc** [comment]
https://github.com/dora-js/dora-plugin-proxy#规则定义
看下整体个规则定义，不要只看这一个规则的点。左边是 URL，并且需要提取 req 信息，所以 plain text 和 regexp 并没有 express 的规则合适。( 现在的规则匹配和 express 是一致的 )
