### ISSUE TITLE
mock 支持

### ISSUE THREAD

**Issue by sorrycc** [dora-js/dora-plugin-proxy#2]
基于 `proxy.config.js`，扩展类型为 plainObject 的情况，支持 [Mock.js](http://mockjs.com/)。

使用方式如下：

``` javascript
var movie = {
  'id|+1': 1,
  'name': '@Name',
};

module.exports = {
  'GET /movies': {data|5: [movie], success: true},
  'GET /movie/:id': {data: movie, success: true},
}
```

请求 `/movies`，返回：

``` javascript
{
    "success": true,
    "data": [
        {
            "id": 3,
            "name": "Gary Wilson"
        },
        {
            "id": 2,
            "name": "Lisa Thomas"
        },
        {
            "id": 2,
            "name": "Ronald Lewis"
        },
        {
            "id": 3,
            "name": "Jason Robinson"
        },
        {
            "id": 5,
            "name": "Karen Lopez"
        }
    ]
}
```

请求 `/movies/3`，返回：

``` javascript
{
    "success": true,
    "data": {
        "id": 3,
        "name": "Melissa Moore"
    }
}
```

**Comment by sorrycc** [comment]
引用 mockjs 的 mock 方法可以直接引文件：

``` javascript
import {mock} from 'mockjs/src/mock';
mock(data)
```

**Comment by sorrycc** [comment]
其他的 mock 数据生成方案：
- http://json-schema.org/
- http://www.json-generator.com/

**Comment by soda-x** [comment]
请求 `/movies/3` ，返回：

``` javascript
{
    "success": true,
    "data": {
        "id": 3,
        "name": "Melissa Moore"
    }
}
```

对于这个的实现 目前考虑到有 几种实现方式 
- 保持既定

``` javascript
var movie = {
  'id|+1': 1,
  'name': '@Name',
};
```

但是在代理层在 使用 `Mock.mock(tmp)` 得到的 json 内部进行截获 并修改.   但是目前能想到的劣势很明显，首先需要在用户配置 `proxy.config.js` 时候去申请将来需要去截获并修改的字段 诸如 `'GET /movie/:data.id': {data: movie, success: true}` , 使用 `data.id` 的含义是申明截获的 object 路径，当然劣势还会有，当一个字段需要在返回数据里多处修改时，以及需要修改的字段在 一个 collection 内.
- 使用 Mock.mock(rurl, function(option){}) 这种方式，即用 function 的方式
- 遇到这种场景，直接推荐用户使用目前 mock 的 function 的方式，如果要支持数据模板，把 Mock.mock 传递进去即可.

**Comment by sorrycc** [comment]
请求 `/movies/3` 是否返回 id 为 3 的感觉不是很重要，可以不做处理，有需要让用户自己通过 function 或其他方式实现吧。

**Comment by soda-x** [comment]
确定下 ：
  诸如 分页 场景`'GET /api/:cat' : object`，该方式只是 实现了 `Mock.mock(tmpl)` 的调用, 在分页场景下并不能适用. 因为 `:cat` 抑或 `currentPageNumber` 并不能传递进来

如果要实现上述分页需求 让用户 去用 function 实现 .  即  `'GET /api/:cat' : function` ，在这种模式下 `function` 内传入三个参数 `req, callback ，Mock.mock`  (req 内会注入 params)    ？

**Comment by soda-x** [comment]
如果这样的话  `'GET /api' : object` 显得很单一 o.o

**Comment by sorrycc** [comment]
从使用的角度整理下看怎么用更好呢?

**Comment by soda-x** [comment]
可以我去整理下 各种场景
