### ISSUE TITLE
自定义为 function 时 返回方式和 express 保持一致

### ISSUE THREAD

**Issue by soda-x** [dora-js/dora-plugin-proxy#9]
```
    res
      json(data)
      jsonp(data, name='callback')
      set(key, value)
      status(statusCode)
      end(data)
      mockjs(data)
```

如上

**Comment by sorrycc** [comment]
http://expressjs.com/en/api.html#res

**Comment by sorrycc** [comment]
mockjs 不内置支持了，其他的都已经加了。

**Comment by soda-x** [comment]
快啊！
看了代码 现在 post 传递过来的数据 还没有返回过来吧?

**Comment by soda-x** [comment]
随 form 过来的数据要处理返回
随 send 过来的数据也要处理返回  之前这一块是放在 postData

**Comment by sorrycc** [comment]
现在是在 body 里，看这个用例。
https://github.com/dora-js/dora-plugin-proxy/blob/master/test/index-test.js#L97-L115

**Comment by soda-x** [comment]
好吧 我把两个body弄混了   有一点点混淆 0.0
