### ISSUE TITLE
如何实现 connect-history-api-fallback

### ISSUE THREAD

**Issue by yxqme** [dora-js/dora-plugin-proxy#96]
Middleware to proxy requests through a specified index page, useful for Single Page Applications that utilise the HTML5 History API.

https://github.com/bripkens/connect-history-api-fallback

**Comment by sorrycc** [comment]
https://github.com/dora-js/dora-plugin-browser-history
试试这个。

**Comment by yxqme** [comment]
@sorrycc 使用了dora-plugin-browser-history， 原来dora-plugin-proxy mock的接口 失效了，有参数配置吗，我没找到，例如，传入一个正则，匹配的走dora-plugin-proxy，不匹配的走dora-plugin-browser-history
