### ISSUE TITLE
怎么改端口

### ISSUE THREAD

**Issue by crazyair** [dora-js/dora-plugin-proxy#98]
dora -p 8888 --plugins  proxy 

改完了 端口还是 8989  要怎么写才会改端口

**Comment by sorrycc** [comment]
dora --plugins proxy?port=8888

**Comment by crazyair** [comment]
原来是url传参 md上面也不写  我看源码是query获取的 但是一般的都是 -p  改端口的 思想没改过来！

**Comment by crazyair** [comment]
还是报错 不行

# E:\1mdataweb\1mdata\xlt-wechat-doctor>dora --plugins proxy?port=8888

failed to create cert dir ,please create one by yourself - \Users\hjf.anyproxy_certs\

# this error will not block main thread unless you use https-related features in anyproxy

```
      proxy: load rule from proxy.config.js
```

(node:13020) DeprecationWarning: 'GLOBAL' is deprecated, use 'global'
temp certs cleared
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn E:\1mdataweb\1mdata\xlt-wechat-doctor\node_modules\dora-anyproxy\cert\gen-rootCA.cmd ENOENT
    at exports._errnoException (util.js:953:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Function.Module.runMain (module.js:577:11)
    at startup (node.js:160:18)
    at node.js:449:3

**Comment by sorrycc** [comment]
`dora --plugins "proxy?port=8888"` 带上引号试试。

**Comment by crazyair** [comment]
还是不行  是要创建 anyproxy_certs？  这是什么鬼

**Comment by sorrycc** [comment]
windows 下是比较啃爹。。建议不要用 proxy 了。

**Comment by crazyair** [comment]
那怎么用模拟数据
